pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                script {
                    // Clone the repository from the specified branch
                    git branch: 'Master', credentialsId: 'github-credentials-id', url: 'https://github.com/zee-ham-su/alx-backend-python.git'
                }
                sh 'git branch'
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    // Install dependencies from the requirements file
                    sh 'pip3 install -r messaging_app/requirements.txt'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    // Run tests and generate a report
                    sh 'pytest --junitxml=report.xml messaging_app/tests'
                }
            }
        }
        stage('Publish Report') {
            steps {
                script {
                    // Publish the test report
                    junit 'report.xml'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Define the Docker image name and build the Docker image
                    def dockerImageName = 'hamzasufian2014812/messaging_app'
                    docker.build(dockerImageName)
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Define Docker credentials and image name
                    def dockerImageName = 'hamzasufian2014812/messaging_app'
                    // Ensure the image is pushed to Docker Hub using the stored credentials
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials-id') {
                        docker.image(dockerImageName).push('latest')
                    }
                }
            }
        }
    }
}