pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github-credentials-id', url: 'https://github.com/zee-ham-su/alx-backend-python.git'
                sh 'git branch'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest --junitxml=report.xml messaging_app/tests'
            }
        }
        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Define the Docker image name
                    def dockerImageName = 'hamzasufian2014812/messaging_app'
                    // Build the Docker image
                    docker.build(dockerImageName) // This builds the Docker image
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Define Docker credentials and image name
                    def dockerImageName = 'hamzasufian2014812/messaging_app'
                    // Ensure the image is pushed to Docker Hub using the stored credentials
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials-id') {
                        // Push the image with the 'latest' tag
                        docker.image(dockerImageName).push('latest')
                    }
                }
            }
        }
    }
}
