name: Django CI

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: russ3509
          MYSQL_USER: sufian_hamza
          MYSQL_PASSWORD: russ3509
          MYSQL_DATABASE: m_app_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt

      - name: Run Tests
        env:
          DATABASE_NAME: m_app_db
          DATABASE_USER: sufian_hamza
          DATABASE_PASSWORD: russ3509
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 3306
        run: |
          python manage.py migrate
          python manage.py test
