apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
    version: blue # Start with blue; update to green during deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
